### PR TITLE
Fix: Windows - wrap npm path in quotes, use shell when spawning npm

### LINKED ISSUE #26: Improving windows support
While investigating kentcdodds/webpack-validator#7, I've been looking into this project and it's claim of supporting windows. 

I've cloned the project and run the tests and have noticed a few of things in relation to windows support.

- Using Appveyor builds. This is essential for supporting windows as it allows tests to be run in a windows environment.
- Code coverage. There is a high percentage of code coverage, but I noticed that `spawn-win32.js` isn't in the coverage report.

The actual issue I have discovered is that `which-npm.js` is returning a path like the following
 - `C:\Program Files\nodejs\npm.CMD`

In windows paths are typically normalized to
- `C:\\Program Files\\nodejs\\npm.CMD`

This results in npm complaining with

```
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

I thought this might be an issue in `which`, but it appears `npm` is using this package with no apparent issues...

I'm happy to create pull requests in an attempt to resolve any of these issues

### PR DESCRIPTION
**Pull request by BarryThePenguin**
Fixes #26

### CODE REVIEW

**Comment by mysticatea** [comment]
Thank you very much!

Hmmm, but this PR is not working on my PC.
I'll investigate.

```
     Error: spawn "C:\Users\t-nagashima.AD\nodist\bin\npm.CMD" ENOENT
      at exports._errnoException (util.js:856:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
      at onErrorNT (internal/child_process.js:344:16)
```

**Comment by BarryThePenguin** [comment]
Sure. I didn't think it would be that simple... It could need a check for the existence of a space in the path?

I'm just guessing now though...

**Comment by mysticatea** [comment]
I'm trying to make a test case for this.
And I guess maybe we can use just `npm` (without `which`) if we use `{shell: true}`

**Comment by BarryThePenguin** [comment]
Just a suggestion, would it be worth using an existing cross platform spawn utility like [node-cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async)

**Comment by mysticatea** [comment]
Good idea.

... I'm confusing now....
The current master is passing the test for a path which includes a space.

```
  [common] npm-run-all
    should run tasks even if npm exists at a path which includes a space:
npm: C:\Users\t-nagashima.AD\Documents\GitHub\npm-run-all\test-workspace\spaced bin\npm.CMD
      √ lib version (1727ms)
      √ command version (1705ms)


  2 passing (3s)
```

**Comment by BarryThePenguin** [comment]
Do you have the test available for me to try? What version node are we both running?
I'm on v5.5.0

**Comment by mysticatea** [comment]
Thank you, I pushed it: https://github.com/mysticatea/npm-run-all/tree/fix-for-space

I tried 4.3.2 and 5.7.1

**Comment by mysticatea** [comment]
Sorry, I pushed again.

**Comment by BarryThePenguin** [comment]
Yeah... ok. Tests work here too

image

But not the project this issue originated from...

image

**Comment by mysticatea** [comment]
I confirmed to reproduce it on webpack-validator.

```
C:\Users\t-nagashima.AD\Documents\GitHub\webpack-validator [master]> npm run validate

> webpack-validator@1.0.0-beta.6 validate C:\Users\t-nagashima.AD\Documents\GitHub\webpack-validator
> npm-run-all --parallel lint cover build test:configs --sequential check-coverage

npm: C:\Users\t-nagashima.AD\Documents\GitHub\npm-run-all\test-workspace\spaced bin\npm.CMD

'C:\Users\t-nagashima.AD\Documents\GitHub\npm-run-all\test-workspace\spaced' is not recognized as an internal or external command,
operable program or batch file.
'C:\Users\t-nagashima.AD\Documents\GitHub\npm-run-all\test-workspace\spaced' is not recognized as an internal or external command,
operable program or batch file.
'C:\Users\t-nagashima.AD\Documents\GitHub\npm-run-all\test-workspace\spaced' is not recognized as an internal or external command,
operable program or batch file.
'C:\Users\t-nagashima.AD\Documents\GitHub\npm-run-all\test-workspace\spaced' is not recognized as an internal or external command,
operable program or batch file.
ERROR: lint: None-Zero Exit(1);
```

**Comment by mysticatea** [comment]
OK, I confirmed to resolve this issue with using `cross-spawn-async`.
Though I'm still not sure why the test works, I will make `npm-run-all` using `cross-spawn-async` and release it.

**Comment by mysticatea** [comment]
@BarryThePenguin I really appreciate your works and suggestions!

**Comment by BarryThePenguin** [comment]
:clap: No problem, happy to help. Ping me anytime

**Pull request closed without merging**
